#!/usr/bin/env bash

# Find the directory of this script. https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

if NEUTRON_OPEN_IN_DEFAULT_BROWSER; then   
    cp $DIR/open-in-default-browser /tmp/open-in-default-browser
fi

sed -i "s:NEUTRON_OPEN_IN_DEFAULT_BROWSER_EXTENSION_LOCATION:file\:\/\/${DIR}\/open_in_default_browser-1.0\.zip:g" $DIR/distribution/policies.json

$DIR/NEUTRON_INTERNAL_APP_NAME $1

if NEUTRON_OPEN_IN_DEFAULT_BROWSER; then   
    rm /tmp/open-in-default-browser
fi